version: "3.9"

services:
  api:
    build: .
    container_name: drivenow_api
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: "sqlite:///./vehicles.db"

    volumes:
      - ./logs:/app/logs
      - ./vehicles.db:/app/vehicles.db

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
